### ISSUE TITLE
LoginActivity crash when run in Android 4.2.2, API 17

### ISSUE THREAD

**Issue by dansuse** [openMF/Fineract-CN-mobile#217]
**Summary:** 

When launch in (Android 4.2.2, API 17), there is an error "Unfortunately, Fineract 2.0 has stopped".

**Steps to reproduce:** 

Just launch the app in (Android 4.2.2, API 17), then the app will immediately crash.

**Expected behavior:** 

App should run with no error.

**Observed behavior:** 

This is the log cat error 
`03-26 23:40:08.584 27308-27308/org.apache.fineract E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{org.apache.fineract/org.apache.fineract.ui.online.login.LoginActivity}: android.view.InflateException: Binary XML file line #0: Error inflating class EditText
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2365)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
                                                                         at android.app.ActivityThread.access$600(ActivityThread.java:166)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                         at android.os.Looper.loop(Looper.java:194)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5427)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:525)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class EditText
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                         at org.apache.fineract.ui.base.FineractBaseActivity.setContentView(FineractBaseActivity.java:45)
                                                                         at org.apache.fineract.ui.online.login.LoginActivity.onCreate(LoginActivity.java:58)
                                                                         at android.app.Activity.performCreate(Activity.java:5203)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1156)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2329)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429) 
                                                                         at android.app.ActivityThread.access$600(ActivityThread.java:166) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                         at android.os.Looper.loop(Looper.java:194) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5427) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                      Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_tenant_black_24dp.xml from drawable resource ID #0x7f08009d
                                                                         at android.content.res.Resources.loadDrawable(Resources.java:2137)
                                                                         at android.content.res.TypedArray.getDrawable(TypedArray.java:604)
                                                                         at android.widget.TextView.<init>(TextView.java:783)
                                                                         at android.widget.EditText.<init>(EditText.java:60)
                                                                         at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:64)
                                                                         at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:60)
                                                                         at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:112)
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1016)
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1073)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:675)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                         at org.apache.fineract.ui.base.FineractBaseActivity.setContentView(FineractBaseActivity.java:45) 
                                                                         at org.apache.fineract.ui.online.login.LoginActivity.onCreate(LoginActivity.java:58) 
                                                                         at android.app.Activity.performCreate(Activity.java:5203) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1156) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2329) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429) 
                                                                         at android.app.ActivityThread.access$600(ActivityThread.java:166) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                         at android.os.Looper.loop(Looper.java:194) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5427) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                      Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #0: invalid drawable tag vector
                                                                         at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:881)
                                                                         at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
                                                                         at android.content.res.Resources.loadDrawable(Resources.java:2134)
                                                                         at android.content.res.TypedArray.getDrawable(TypedArray.java:604) 
                                                                         at android.widget.TextView.<init>(TextView.java:783) 
                                                                         at android.widget.EditText.<init>(EditText.java:60) 
                                                                         at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:64) 
                                                                         at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:60) 
                                                                         at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:112) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1016) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1073) 
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:675) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                         at org.apache.fineract.ui.base.FineractBaseActivity.setContentView(FineractBaseActivity.java:45) 
                                                                         at org.apache.fineract.ui.online.login.LoginActivity.onCreate(LoginActivity.java:58) 
                                                                         at android.app.Activity.performCreate(Activity.java:5203) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1156) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2329) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429) 
                                                                         at android.app.ActivityThread.access$600(ActivityThread.java:166) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                         at android.os.Looper.loop(Looper.java:194) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5427) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                         at dalvik.system.NativeStart.main(Native Method) `

**Device and Android version:** 

Lenovo A3000 -> Android 4.2.2, API 17 -> Stock ROM from the manufacturer
Oppo R2001 -> Android 4.2.2, API 17 -> Stock ROM from the manufacturer

**Screenshots:** 

No screenshot needed

**Comment by RahulPrajapati97** [comment]
@dansuse Can you give me the apk of this app because I am using the apk of github which is not work properly.
